# Generated by Erlang.mk. Edit at your own risk!

src/lager_nklog_backend.erl:: /home/james/local/git/2600hz/erlang-nklib/deps/lager/include/lager.hrl; @touch $@
src/nklib.erl:: include/nklib.hrl; @touch $@
src/nklib_date.erl:: /home/james/local/git/2600hz/erlang-nklib/deps/qdate_localtime/include/tz_database.hrl include/nklib.hrl; @touch $@
src/nklib_gen_server.erl:: include/nklib.hrl; @touch $@
src/nklib_links.erl:: include/nklib.hrl; @touch $@
src/nklib_log_gelf.erl:: src/nklib_log.erl; @touch $@
src/nklib_parse.erl:: include/nklib.hrl; @touch $@
src/nklib_parse_uri.erl:: include/nklib.hrl; @touch $@
src/nklib_syntax.erl:: include/nklib.hrl; @touch $@
src/nklib_unparse.erl:: include/nklib.hrl; @touch $@
src/nklib_util.erl:: include/nklib.hrl src/nklib_parse_trans_vsn.erl; @touch $@

COMPILE_FIRST += nklib_parse_trans_vsn nklib_log
